### ISSUE TITLE
Newest JLink software (5.10h+) causes programming script to hang

### ISSUE THREAD

**Issue by estutzenberger** [rigado/bootloader-tools#1]
The recent releases of JLink software have completely removed support for auto connection and detection of IC.  The JLink software waits for additional input.  Our programming script appears to hang when this is the case.  In reality, it hangs because JLink wants more input.  I am testing a fix and will push to this repository when ready.

**Comment by estutzenberger** [comment]
@rigado/moduleclients @rigado/rigado 
The programming scripts have been updated to work with the most recent versions of the Segger JLink tools.

**Comment by sk1143** [comment]
Hi Eric,

Thank you for letting us know.

chieh

Date: Thu, 11 Feb 2016 11:07:54 -0800
