### ISSUE TITLE
Genimage: sudo brew install cryptopp

### ISSUE THREAD

**Issue by rph8** [rigado/bootloader-tools#2]
Just a small thing: You should not use brew install with but without sudo on OS X.
brew itself says:

```
Error: Cowardly refusing to 'sudo brew install'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```

**Comment by estutzenberger** [comment]
Thanks!

It looks like that particular documentation is out of date.  Installation of cryptopp is not required since we provide signimage as a precompiled binary.  Sorry for the confusion.
