### ISSUE TITLE
Bootloader V3.2.1 request

### ISSUE THREAD

**Issue by THLN33** [rigado/bootloader-tools#9]
Hello,

I checked some nrf52 devices I bought, and they have a rigdfu bootloader version 3.2.1.
Could you please update your repository with the very last up-to-date binary version.
	(bootloader-tools/programming/binaries/)

Thanks

		E:\Devl\js\tests>..\node-v6.10.0-win-x64\node.exe dfu.js -t
		Scanning for DFU device...
		Found: name RigDfu, address c0ab6cf32abc, 41c8903017564c3093cca8fcc2fb0202 , RSSI -61
		Connecting...
		Discovering services...
		41c8903117564c3093cca8fcc2fb0202
		41c8903217564c3093cca8fcc2fb0202
		2a26
		Bootloader firmware revision: 3.2.1 (43)
		Test mode; disconnecting.

**Comment by estutzenberger** [comment]
Hi, this will be coming out today.

**Comment by estutzenberger** [comment]
RigDFU v3.2.3 was released today as part of v3.0.0.  Please see the known errata documentation in the rigdfu_errata folder if you need to update RigDFU v3.2.1 without a JLink.
